# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ow4Yfl04lffHE9R3mAS264Q7NBjcoyf

### perfect number
"""

# perfect number
n = int(input("enter a value"))
sum = 0
for i in range(1,n):
  if n%i==0:
    sum+=i
if(sum==n):
    print("perfect number")
else:
   print(" not perfect number")